/* Candidate palettes for the v2 re-theme. Each is a self-contained token set so
   the theme studio can render a live mini-homepage without touching the global
   Tailwind tokens. `onAccent` is the text color that sits on an accent button. */
export const themes = [
  {
    id: 'clay',
    name: 'Clay (current)',
    vibe: 'The warm editorial base — Claude’s terracotta. Shown for comparison.',
    dark: false,
    paper: '#fbf7f0',
    cream: '#f7f1e7',
    cream2: '#efe6d6',
    ink: '#1b1714',
    inkSoft: '#2a2420',
    muted: '#8a7f72',
    line: '#e6ddd0',
    accent: '#cc785c',
    accentDeep: '#b4593d',
    secondary: '#c69749',
    onAccent: '#ffffff',
  },
  {
    id: 'diplomatic',
    name: 'Diplomatic — Navy & Brass',
    vibe: 'Navy headings, brass flourishes on ivory. UN / Oxford / executive.',
    dark: false,
    paper: '#f7f5ef',
    cream: '#efeae0',
    cream2: '#e4ddcf',
    ink: '#16202e',
    inkSoft: '#2b3540',
    muted: '#76808c',
    line: '#e2dccf',
    accent: '#1f3b5e',
    accentDeep: '#15304f',
    secondary: '#b0883f',
    onAccent: '#ffffff',
  },
  {
    id: 'cinnabar',
    name: 'Cinnabar — Heritage Red',
    vibe: 'Chinese seal-red + gold on bone paper. Bold, warm, personal.',
    dark: false,
    paper: '#f8f4ec',
    cream: '#f0e9db',
    cream2: '#e6dccb',
    ink: '#1a130f',
    inkSoft: '#332a22',
    muted: '#8a7d6c',
    line: '#e7dcc9',
    accent: '#b53a2b',
    accentDeep: '#97301f',
    secondary: '#c69749',
    onAccent: '#ffffff',
  },
  {
    id: 'ink-brass',
    name: 'Ink & Brass — Monochrome',
    vibe: 'Near black-on-ivory with one restrained brass accent. Timeless.',
    dark: false,
    paper: '#f6f3ec',
    cream: '#ece7dc',
    cream2: '#e0d8c9',
    ink: '#141210',
    inkSoft: '#2c2823',
    muted: '#837a6c',
    line: '#e4dccd',
    accent: '#a9824a',
    accentDeep: '#8a6838',
    secondary: '#141210',
    onAccent: '#141210',
  },
  {
    id: 'teal-ivory',
    name: 'Teal & Ivory',
    vibe: 'Deep teal accent + warm gold on ivory. Your color, in daylight.',
    dark: false,
    paper: '#f4f4ef',
    cream: '#e9e8df',
    cream2: '#dde0d6',
    ink: '#14201e',
    inkSoft: '#2a3a37',
    muted: '#79857f',
    line: '#dde2da',
    accent: '#0f5f5a',
    accentDeep: '#0b4a46',
    secondary: '#b0883f',
    onAccent: '#ffffff',
  },
  {
    id: 'midnight-teal',
    name: 'Midnight Teal (dark)',
    vibe: 'Deep teal-charcoal, off-white type, bright teal accent. Your color, bold.',
    dark: true,
    paper: '#0f1c1b',
    cream: '#152725',
    cream2: '#1c302d',
    ink: '#eef2ee',
    inkSoft: '#c9d3cf',
    muted: '#8aa39d',
    line: '#294441',
    accent: '#3fb6a8',
    accentDeep: '#2f9488',
    secondary: '#d8b768',
    onAccent: '#0f1c1b',
  },
]
